### ISSUE TITLE
Fail: AttributeError: module 'collections' has no attribute 'Container' 

### ISSUE THREAD

**Issue by Vladzrabbit** [scanny/python-pptx#750]
Hi, I try to start "python-pptx", but i have Error: 
AttributeError: module 'collections' has no attribute 'Container' 
in File "...\lib\site-packages\pptx\__init__.py", line 14, in <module>

Use Python 3.10, python-pptx (0.6.21), lxmx (4.6.3).

Please, help me.

**Comment by MartinPacker** [comment]
Thanks @scanny. Looking at the Python docs this code looks like it should work on 3.10. I checked the 3.10 docs and there's no sign even of a deprecation.

(The docs got overhauled sometime between 3.8 and 3.9 - expanding with examples.)

I'm not - at least for the moment - going to flag 3.10 as problematic for python-pptx or my package that relies on it.
