### ISSUE TITLE
Replicate a slide in version 0.6.1

### ISSUE THREAD

**Issue by brownmk** [scanny/python-pptx#238]
I was able to use a workaround code provided by robintw and zhong2000 to duplicate slides
(see issue #132 and #232)

The workaround works well with version 0.5.8. However, it no longer works with 0.6.1
The error is associated with the line: for key, value in six.iteritems(source.rels):
AttributeError: 'Slide' object has no attribute 'rels'

rels is no longer an attribute for a Slide object, any suggestion on how to patch this code in order to make it work under 0.6.1?

Thanks!

Test code is attached below:
```
import pptx
import copy
import six

def _get_blank_slide_layout(pres):
     layout_items_count = [len(layout.placeholders) for layout in pres.slide_layouts]
     min_items = min(layout_items_count)
     blank_layout_id = layout_items_count.index(min_items)
     return pres.slide_layouts[blank_layout_id]

def copy_slide(pres,pres1,index):
     source = pres.slides[index]
     blank_slide_layout = _get_blank_slide_layout(pres)
     dest = pres1.slides.add_slide(blank_slide_layout)

     for shp in source.shapes:
          el = shp.element
          newel = copy.deepcopy(el)
          dest.shapes._spTree.insert_element_before(newel, 'p:extLst')

          for key, value in six.iteritems(source.rels):
                     # Make sure we don't copy a notesSlide relation as that won't exist
                   if not "notesSlide" in value.reltype:
                           dest.rels.add_relationship(value.reltype, value._target, value.rId)
          return dest
from pptx import Presentation
SLD_LAYOUT_TITLE_AND_CONTENT = 1
prs = Presentation()
slide_layout = prs.slide_layouts[SLD_LAYOUT_TITLE_AND_CONTENT]
slide = prs.slides.add_slide(slide_layout)
copy_slide(prs, prs, 0)


```

**Comment by scanny** [comment]
Yes, a new class `SlidePart` was extracted from `Slide` a while back. So you need this to get to the `RelationshipCollection` (`.rels`) for the slide part:

```python
slide.part.rels
```

Let us know if that works for you :)

**Comment by brownmk** [comment]
Works! Thanks!

**Comment by scanny** [comment]
Glad to hear it :)

**Comment by Quanjiang** [comment]
Can't understand why those code can be work ?

`def copy_slide(pres,pres1,index):
     source = pres.slides[index]
     blank_slide_layout = _get_blank_slide_layout(pres)
     dest = pres1.slides.add_slide(blank_slide_layout)

     for shp in source.shapes:
          el = shp.element
          newel = copy.deepcopy(el)
          dest.shapes._spTree.insert_element_before(newel, 'p:extLst')

          for key, value in six.iteritems(source.rels):
                     # Make sure we don't copy a notesSlide relation as that won't exist
                   if not "notesSlide" in value.reltype:
                           dest.rels.add_relationship(value.reltype, value._target, value.rId)
          return dest # here break look before all shapes copy to new slide. If I move this return out of 'for shp in' the pptx with all shape copy can't open by PowerPoint.`

**Comment by ApJai** [comment]
How to reorder slides in existing PPT ex., [Slide1, S2, S3, S4, S5, S6, S7, S8, S9] to [Slide1, S4, S7, S2, S5, S8, S3, S6, S9]

**Comment by MartinPacker** [comment]
If we're going to be able to reorder slides we're going to also want to be able to delete them.

**Comment by MalteHerrmann** [comment]
> If we're going to be able to reorder slides we're going to also want to be able to delete them.

I think it is possible, i think i've gotten the answer from StackOverflow if I remember this correctly.
    
    import numpy as np

    def delete_slides(prs, indices): # prs: Presentation object, indices: list of ints
        indices_np = np.flipud(np.sort(np.array(indices))) # indices should be erased backwards

        xml_slds = prs.slides._sldIdLst
        slds = list(xml_slds)

        try:
            for idx in indices_np:
                xml_slds.remove(slds[idx])
        except TypeError: # if indices_np is only 1 item and not iterable
            xml_slds.remove(slds[indices_np])

        return prs
