### ISSUE TITLE
AttributeError: 'BarSeries' object has no attribute 'fill'

### ISSUE THREAD

**Issue by savithamr** [scanny/python-pptx#424]
Hi, 
   There is a bug in 0.6.11 while using fill for bar charts
  AttributeError: 'BarSeries' object has no attribute 'fill'
The same code works on 0.6.2 version

But the hyperlink feature to jump to a specific slide
 i.e
     target_slide = prs.slides[10]
     shape.click_action.target_slide = target_slide
doesn't work in 0.6.2. Errors out with: AttributeError: can't set attribute 

Need to have both features in the project.
Thanks,

**Comment by savithamr** [comment]
Apologies. 
Please close this issue. The documentation is not updated at
http://python-pptx.readthedocs.io/en/latest/dev/analysis/cht-series.html

The below code worked:
graphic_frame = slide.shapes.add_chart(
    XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data
)
chart = graphic_frame.chart
plot = chart.plots[0]
series = plot.series[0]
fill = series.format.fill
fill.solid()
fill.fore_color.rgb = RGBColor(0x3F, 0x2C, 0x36)

Thanks

**Comment by scanny** [comment]
Documentation updated, should appear in next release.
